# Artificial Neural Network.

In [1]:
# Let's import the libraries required for preprocessing. 

import numpy as np
import pandas as pd
import tensorflow as tf 

In [2]:
tf.__version__

'2.0.0'

In [4]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding Categorical Data. 


In [8]:
# Lets encode for gender. 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [10]:
# Lets encode for the "Geographical" column 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder() , [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Splitting the dataset into training and test. 

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size =0.2, random_state= 42)

# Feature scaling. 

In [13]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# Part 2

# Building ANN. 

In [15]:
# Initializing ann. 
ann = tf.keras.models.Sequential()

In [16]:
# Adding the first input layer and the first hidden layer. 
ann.add(tf.keras.layers.Dense(units= 6, activation= "relu"))

In [17]:
#Adding second hidden layer. 
ann.add(tf.keras.layers.Dense(units= 6, activation= "relu"))

In [18]:
#Adding the output layer. 
ann.add(tf.keras.layers.Dense(units =1, activation= 'sigmoid'))

# Part 3

# Training the ANN

In [21]:
# Compliling the ann. 
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [22]:
# training ANN on the training set. 
ann.fit(X_train,y_train, batch_size=32, epochs= 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 3s 370us/sample - loss: 0.5893 - accuracy: 0.7487
Epoch 2/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4726 - accuracy: 0.79 - 0s 62us/sample - loss: 0.4724 - accuracy: 0.7987
Epoch 3/100
8000/8000 [==============================] - 0s 62us/sample - loss: 0.4452 - accuracy: 0.8065
Epoch 4/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4342 - accuracy: 0.8108
Epoch 5/100
8000/8000 [==============================] - 1s 89us/sample - loss: 0.4278 - accuracy: 0.8135
Epoch 6/100
8000/8000 [==============================] - 1s 77us/sample - loss: 0.4228 - accuracy: 0.8170
Epoch 7/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4183 - accuracy: 0.8211
Epoch 8/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.4143 - accuracy: 0.8257
Epoch 9/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.4102 

8000/8000 [==============================] - 0s 58us/sample - loss: 0.3321 - accuracy: 0.8629
Epoch 77/100
8000/8000 [==============================] - 0s 58us/sample - loss: 0.3318 - accuracy: 0.8630s - loss: 0.3305 - accuracy: 0.86
Epoch 78/100
8000/8000 [==============================] - 0s 57us/sample - loss: 0.3320 - accuracy: 0.8625
Epoch 79/100
8000/8000 [==============================] - 0s 62us/sample - loss: 0.3319 - accuracy: 0.8621
Epoch 80/100
8000/8000 [==============================] - 0s 59us/sample - loss: 0.3316 - accuracy: 0.8621
Epoch 81/100
8000/8000 [==============================] - 0s 58us/sample - loss: 0.3321 - accuracy: 0.8621
Epoch 82/100
8000/8000 [==============================] - 0s 61us/sample - loss: 0.3315 - accuracy: 0.8629
Epoch 83/100
8000/8000 [==============================] - 0s 57us/sample - loss: 0.3318 - accuracy: 0.8622
Epoch 84/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3314 - accuracy: 0.8637
Epoch 85/100
8000

# Part 4 

# Making predictions and evaluating the model. 

In [23]:
# Lets predict on a row

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


# Predicting on test set results. 

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


# Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1554   53]
 [ 211  182]]


0.868